Domain layer finished
albertoag128/MoviesApp pull request #1
Opened 2022-11-07 19:31 UTC by albertoag128

## DESCRIPTION
This pull request is about showing how the domain layer has been implemented. In first instance we have our domain models, some use cases and also a repository which will be providing methods for the use cases.

## HOW IT WAS IMPLEMENTED
We can find here 4 files:
-->Models: this file will contain our domain model of movies and we could also add here some logic business.
-->Use cases: we have two of them; the one that has been created in order to get the movies feed and the second one focused on find just one movie by its id. Both of this files contains its own data class, because in the end we just want to get the information that we will be showing on the UI through the use cases.
-->MoviesRepository: this will be our interface to define what are the methods that we will be using in our use cases.

## KEYWORDS
Domain, Models, Repository, Data Classes, Use Cases, Interface, Separation of concerns, Clean arquitecture

## SCREENSHOTS
Domain structure
![imagen](https://user-images.githubusercontent.com/91797204/200397977-a67b02d4-c2bf-475a-8225-a6721664cecc.png)

2022-11-07 21:36 UTC, josem-perram requested changes
The PR is ok, just some comments about where putting the model of use case.

2022-11-07 21:36 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/domain/GetMoviesFeedUseCase.kt
> +data class MoviesFeed(val poster:String, val title:String, val year:String, val rating:String)
MoviesFeed is the response of use case so it should be inside the use case.

2022-11-07 21:36 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/domain/GetSingleMovieUseCase.kt
> +data class MovieDetail(val poster:String, val title:String, val plot:String, val genre:String, val rating: String, val year:String)
the same, MovieDetail should be inside the use case ;)

2022-11-08 07:54 UTC, albertoag128 commented
The changes requested have been applied to the project moving the data classes of the use cases inside the use cases. I will close this pull request with this comment, and after that, I will delete domain branch and merge it with master.

2022-11-08 07:54 UTC, merged