Feed presentation
albertoag128/MoviesApp pull request #9
Opened 2022-11-10 18:22 UTC by albertoag128

## DESCRIPTION
This pull request shows all the work done referring to the presentation part, focusing in feed.

## HOW IT WAS IMPLEMENTED
 We have decide to go for an observer pattern that will replace callbacks in order to wait for the data and let us know when its ready. 
We will also be using fragments, instead of activities and support them with a navigation graph that will setup our "home page". Respecting binding the information, we will generate a view model from the use case and this view model will interact with our fragment. 
In the end we will "print" our feed thanks to a recycler view linked to an adapter and also a view holder. 

## DISCLAIMER
Not all the images can be load because of their own URL, although the result based on the purposed objectives has been achieved.
I also want to apologize due to the quantity of files created or modified, I do not know why but firebase is included, so feel free to ignore it as I haven't changed nothing but the merge wasn't as expected. Regarding the rest of files, hierarchy modifications as suspend, or some corrections have increased the volume of the pull request.

## KEYWORDS
Presentation, UI, ViewModel, Factory, Fragments, Navigation, Activity.

## SCREENSHOTS
![WhatsApp Image 2022-11-10 at 19 01 07](https://user-images.githubusercontent.com/91797204/201175453-4ec9bf25-6e33-47c3-a6f5-e910fc6cf659.jpeg)

2022-11-11 00:10 UTC, josem-perram requested changes
Some comments and waiting for the next PR in order to check the navigation component ;)

2022-11-11 00:10 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/data/MoviesDataRepository.kt
> +    private val localSource: MovieRoomLocalDataSource,
just a recommendation regarding namings:
Source Android documentation:
![image](https://user-images.githubusercontent.com/93087250/201231595-94bb1c0c-67f1-460a-a8c4-10be091ae304.png)

**Check this part:**
Don't name the data source based on an implementation detail—for example, UserSharedPreferencesDataSource—because repositories that use that data source shouldn't know how the data is saved.

2022-11-11 00:10 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/data/MoviesDataRepository.kt
> +        if(localSource.getAllMovies().isNullOrEmpty()){
Warning!!! you execute localSource.getAllMovies() twice 0_0

2022-11-11 00:10 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/data/MoviesDataRepository.kt
> +        return localSource.getMovieById(id)
the same, ``localSource.getMovieById(id)`` twice

2022-11-11 08:41 UTC, albertoag128 commented on app/src/main/java/com/example/moviesapp/data/MoviesDataRepository.kt
> +        return localSource.getMovieById(id)
Yeaah, now I am reading it, makes sense to do not name the data source based on an implementation detail, I will take care of that as well as executing just one time the calls of the different sources in MoviesDataRepository. Thank you for the feedback

2022-11-11 09:08 UTC, albertoag128 commented
## Changes requested done and applied.
I just did some renaming over the classes that are going to interact with our MoviesDataRepository and dont need to specify the detail of the data source. Also I have optimized MoviesDataRepository by making the repo call our local source just one time instead of two.
You can find all the changed in the last commit.

2022-11-16 23:16 UTC, josem-perram approved these changes
🚀 Aunque hay muchas clases nuevas, las clases modificadas que son debido al suspend.

2022-11-16 23:16 UTC, josem-perram commented on app/src/main/java/com/example/moviesapp/data/MoviesDataRepository.kt
> +        if(movie == null){
Kotlin code!

2022-11-17 08:49 UTC, merged